---
title: "My_R_Practices1"
output: html_document
date: "2023-03-17"
---

```{r}
getwd()
setwd("C:\\Data Science\\My_R_Projects\\Time_Series")
resp1 <- read.csv("section 1/Resp1.csv",header = T)
resp1
head(resp1)
str(resp1)
```

```{r}
winer1 <-read.csv("section 1/winequality-red.csv",header = T,sep = ";")
winer1 <-read.table("section 1/winequality-red.csv",header = T,sep = ";")
#both lines will read the data from the "winequality-red.csv" file, with the only difference being that read.csv() assumes that the data is in a CSV format, while read.table() allows you to specify the separator character.
head(winer1)
summary(winer1)
```

```{r}
library(readxl)
dfb <- read_excel("section 1/boston1.xls")
head(dfb)
summary(dfb)
```

```{r}
library(MASS)
data()
```

```{r}
data("airquality")
??airquality
str(airquality)
head(airquality)
summary(airquality)
```

```{r}
aq = na.omit(airquality) #remove rows containing NAs
summary(aq)
```

```{r}
aq2 <- airquality[complete.cases(airquality), ] #only retain non-NA rows

head(aq2)
summary(aq2)
```

```{r}
## replace NAs with 0
aqty=airquality

aqty[is.na(aqty)]<-0
head(aqty)
summary(aqty)
```

```{r}
# claculate missing values
meanOzone=mean(airquality$Ozone,na.rm=T)
summary(airquality$Ozone)
summary(meanOzone)

## replcae missing values with average values:

# The ifelse() function evaluates a condition and returns one value if the condition is true, and another value if the condition is false.
aqty.fix=ifelse(is.na(airquality$Ozone),meanOzone,airquality$Ozone)
summary(aqty.fix)
```

```{r}
##visualize the patterns of NAs
install.packages("mice")
library(mice)
aqty2=airquality
X11()
md.pattern(aqty2)
#111 observations with no values
```

```{r}
install.packages("VIM")
aqty2=airquality
library(VIM) #visualize the pattern of NAs
mp <- aggr(aqty2, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(aqty2), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
#72.5% observations in the entire data have no missing values
#22.9% missing values in Ozone
```

```{r}
#impute
#500 iterataions of predictive mean mapping for imputing
#5 datasets
install.packages("mice")
library(mice)
im_aqty<- mice(aqty2, m=5, maxit = 50, method = 'pmm', seed = 500)
```

```{r}
summary(im_aqty)
```

```{r}
head(im_aqty$imp$Ozone) #values imputed in ozone
```

```{r}
#get back the completed dataset u
completedData <- complete(im_aqty,1)
head(completedData)
```

```{r}
setwd("C:\\Data Science\\My_R_Projects\\Time_Series")
eco <- read.csv("section 1/countries_ecologicalF.csv",header = T)
eco
head(eco)
str(eco)

```

```{r}
# replace $ and , with blank "" in the n.  and coerce that result to numeric
eco$GDP = as.numeric(gsub("[\\$,]", "", eco$GDP.per.Capita))
# This R code takes a data frame named eco and creates a new column called GDP. The values in the GDP column are obtained by converting the values in an existing column named GDP.per.Capita from characters to numeric values.
# The gsub() function is used to replace any occurrence of the characters "$" and "," in the GDP.per.Capita column with an empty string, i.e., removing them. Then, the as.numeric() function is used to convert the resulting strings to numeric values, which are assigned to the GDP column.

names(eco)
# returns the names of the columns in the eco data frame.
ncol(eco)
```
```{r}

# creating a subset of eco
# The %in% operator is a binary operator in R that returns a logical vector indicating whether each element in the first operand is also present in the second operand. In the code you provided, the %in% operator is used to check whether each element of the names(eco) vector is present in the vector c("Population..millions.","GDP","Grazing.Footprint","HDI", "Carbon.Footprint", "Cropland","Forest.Land","Urban.Land","Total.Biocapacity"). The resulting logical vector indicates which elements of names(eco) match any of the names in the specified vector, and this vector is assigned to the variable mdf. The mdf vector is then used to select only the columns from the eco data frame that have a TRUE value in the mdf vector.
mdf= names(eco) %in% c("Population..millions.", "GDP", 
                      "Grazing.Footprint","HDI","Carbon.Footprint",
                      "Cropland","Forest.Land","Urban.Land","Total.Biocapacity") 

newdata= eco[mdf] # sample for include the above columns
x= eco[!mdf] # sample for exclude the above columns
```

```{r}
head(newdata)
str(newdata)
newdata=na.omit(newdata)
summary(newdata)
head(newdata)

```

```{r}
# This R code renames a column in a dataset called newdata. Specifically, it changes the name of a column from "Population..millions." to "Population". To do this, the code first selects the names of all the columns in newdata using names(newdata). It then uses a logical comparison (==) to check which of these column names are equal to the string "Population..millions.". The result of this comparison is a logical vector with TRUE values for the column names that match "Population..millions." and FALSE values for the others. The code then uses this logical vector to select the column name that matches and assigns the new name "Population" to it using the assignment operator (=).
names(newdata)[names(newdata)=="Population..millions."] ="Population"

names(newdata)[names(newdata)=="Total.Biocapacity"] ="BiocapacityT"

head(newdata)

write.csv(newdata,"biocap.csv") #store dataframe in a csv
```

